### ISSUE TITLE
How can I add some objects into the Server-sided collection?

### ISSUE THREAD

**Issue by acidsound** [Q42/DDP-Server-Reactive#5]
simply I wrote code like this
```
DDPServer = require 'ddp-server-reactive'
server = new DDPServer 3000
console.log "init"
Messages = server.publish 'messages'
server.methods
  addMessage: (msg)->
    console.log Messages
    console.log "collection size: #{Messages.length}"
    Messages.push
      message: msg
      createdAt: Date.now()
```
but Messages.push doesn't works. because `typeof Messages` is object. not array.
I want to receive "added" messages from client. any idea?

**Comment by marcuzy** [comment]
Messages is not array. Messages is object.
https://github.com/Q42/DDP-Server-Reactive/blob/master/lib.js#L162
https://github.com/Q42/DDP-Server-Reactive/blob/master/lib.js#L212

``` js
let id = 0;
server.methods({
  addMessage: msg => {
   Messages[id++] = {message: msg, createdAt: Date.now()};
  }
})
```

**Comment by acidsound** [comment]
I know as described :) 
I just wonder how to get "added" message in client. not "changed"

**Comment by sjoerdvisscher** [comment]
You should get the "added" message with the code from marcuzy.

**Comment by marcuzy** [comment]
> I want to receive "added" messages **from client**.?

or

> just wonder how to get "added" message **in client**

What you want?)

DDP-Server-Reactive can publish collections (send data to client) and receive method calls. (Server side)
[ddp.js](https://github.com/mondora/ddp.jsl) (or other ddp client) can receive published collections and send method calls. (Client side)

**Comment by acidsound** [comment]
I have some misunderstanding.
`Proxy` is so fantastic!

```
DDPServer = require 'ddp-server-reactive'
server = new DDPServer
Messages = server.publish 'messages'
server.methods
  addMessage: (msg)->
    seq=(Object.keys Messages).length
    Messages[seq]=
      message: msg
      createdAt: Date.now()
    seq
```

I just added some code. works great!
Thanks for your Awesome project 💯 💯 💯 👍
